Repository WildCodeSchool/healthymood-front, pull requests merged in 2020-07, with the labels that each got.

#43 Feature/us37bis
  package-lock.json
  package.json
  public/favicon.ico
  src/App.js
  src/Components/ArticleContent.js
  src/Components/Recipe.js
  src/Components/Search.js
  src/Components/SmallRecipe.js
  src/Components/SocialMediaArticle.js
  src/Components/SocialMediaRecipe.js
  src/Pages/RecipesPage.js
  src/Services/Api.js
  src/Styles/App.css
  src/Styles/ArticleContent.css
  src/Styles/Search.css
  src/Styles/SmallRecipe.css
  src/Styles/SocialMedia.css
Labels: Reviewed

#45 Feature/us auth
  package-lock.json
  package.json
  public/favicon.icon.png
  public/icon-128x128.png
  public/icon-144x144.png
  public/icon-152x152.png
  public/icon-192x192.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/icon-72x72.png
  public/icon-96x96.png
  public/index.html
  public/manifest.json
  src/App.js
  src/Components/Menu.js
  src/Components/Search.js
  src/Components/TopNavBar.js
  src/Context/authContext.js
  src/MenuElements.json
  src/Pages/Login.js
  src/Pages/MonCompte.js
  src/Pages/Register.js
  src/Services/API.js
  src/Services/Api.js
  src/Styles/Login.css
  src/Styles/Register.css
  src/logo.svg
Labels: Reviewed

#46 Feature/hotfix pwa
  public/favicon.ico
  public/manifest.json
  src/App.js
  src/Components/Search.js
  src/Components/pwa.js
  src/Styles/Pwa.css
  src/index.js
Labels: To Be Reviewed

#48 Hotfix/scroll to top
  src/App.js
  src/Scripts/ScrollToTop.js
Labels: Reviewed

#52 Feature/us15ter
  package-lock.json
  package.json
  src/Components/CategoriesList.js
  src/Components/Recipe.js
  src/Components/Search.js
  src/Components/SmallRecipe.js
  src/Components/SocialMediaRecipe.js
  src/Components/TagSelect.js
  src/MenuElements.json
  src/Pages/RecipesPage.js
  src/Styles/Carousel.css
  src/Styles/CategoriesList.css
  src/Styles/Recipe.css
  src/Styles/Search.css
  src/Styles/SmallRecipe.css
  src/Styles/Variables.css
  src/index.js
Labels: To Be Reviewed

#66 Hotfix/geoffroy
  src/App.js
  src/Components/ArticleContent.js
  src/Components/Recipe.js
  src/Components/SmallArticle.js
  src/Components/SmallRecipe.js
  src/Images/default-banner.jpg
  src/Pages/Article.js
  src/Styles/Header.css
Labels: Reviewed

#69 Debug/regex miniatures
  src/Components/SmallArticle.js
  src/Components/SmallRecipe.js
  src/Services/API.js
Labels: Reviewed

#68 css text caroussel
  src/Components/Carousel.js
  src/Styles/Carousel.css
Labels: Reviewed

#65 Hotfix/recipe form
  package-lock.json
  package.json
  src/Components/SendFormRecipe.js
Labels: Correction done

#74 Hotfix/recipe search link
  package-lock.json
  src/Components/Search.js
  src/Pages/RecipesPage.js
  src/Styles/RecipesPage.css
  src/Styles/Search.css
Labels: Reviewed

#78 Debug/recipes when no results
  src/Components/RecipesSuggestion.js
  src/Components/Search.js
  src/Pages/AdvicesAndTricks.js
  src/Pages/RecipesPage.js
  src/Styles/RecipesSuggestion.css
  src/Styles/Search.css
Labels: Reviewed

#79 updated css for content images width
  src/Pages/Pages.js
  src/Styles/Article.css
  src/Styles/Pages.css
  src/Styles/Recipe.css
Labels: Reviewed

#76 Fix/authentif
  src/App.js
  src/Components/ArticleContent.js
  src/Components/Footer.js
  src/Components/Recipe.js
  src/Components/Search.js
  src/Components/SmallRecipe.js
  src/Pages/AdvicesAndTricks.js
  src/Pages/ConseilsAstuces.js
  src/Pages/FavoriteUser.js
  src/Pages/RecipesPage.js
Labels: Reviewed
